blank_issues_enabled: false
contact_links:
  - name: â“ Soporte General
    url: https://github.com/KrlozMedina/Techfolio/issues/new/choose
    about: Si tienes dudas o preguntas generales, usa esta opciÃ³n.
  - name: ğŸ›¡ Reportar problema de seguridad
    url: mailto:kamedinal16@outlook.com
    about: Si detectas una vulnerabilidad de seguridad, contÃ¡ctanos por email.
