blank_issues_enabled: false

contact_links:
  - name: â“ Soporte General
    url: https://github.com/KrlozMedina/Techfolio/discussions
    about: Preguntas generales, ideas o dudas sobre el proyecto.

  - name: ğŸ›¡ Reportar problema de seguridad
    url: mailto:kamedinal16@outlook.com
    about: Reporta vulnerabilidades de seguridad de forma responsable.
